### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by srevay** [sevenfx/fastai_audio#7]
Can you add a license file to clear up if this is open source or not?

**Comment by jhartquist** [comment]
Yes, sorry about that.  I just added the same one as fastai.  

Also, you may be better off using https://github.com/mogwai/fastai_audio
and potentially https://github.com/rbracco/fastai2_audio in a few months when fastai2 is released.  This repo is out of date and I may be contributing to those projects in an effort to have them integrated into the main fastai library.
